import { HtmlToPdf } from "html-toolkit";
import { NextRequest, NextResponse } from "next/server";

export const GET = async (req: NextRequest, res: NextResponse) => {
  try {
    let newArr = Array.from({ length: 50 }, () => "");
    let temp = await newArr.map(async (value, idx) => {
      return await HtmlToPdf(
        `<p class="MsoNormal" style="text-align: center; line-height: normal; margin: 1.0pt 93.0pt 0cm 93.0pt;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; color: black; mso-fareast-language: EN-IN; mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype
        id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
        path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
        <v:stroke joinstyle="miter"/>
        <v:formulas>
         <v:f eqn="if lineDrawn pixelLineWidth 0"/>
         <v:f eqn="sum @0 1 0"/>
         <v:f eqn="sum 0 0 @1"/>
         <v:f eqn="prod @2 1 2"/>
         <v:f eqn="prod @3 21600 pixelWidth"/>
         <v:f eqn="prod @3 21600 pixelHeight"/>
         <v:f eqn="sum @0 0 1"/>
         <v:f eqn="prod @6 1 2"/>
         <v:f eqn="prod @7 21600 pixelWidth"/>
         <v:f eqn="sum @8 21600 0"/>
         <v:f eqn="prod @7 21600 pixelHeight"/>
         <v:f eqn="sum @10 21600 0"/>
        </v:formulas>
        <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
        <o:lock v:ext="edit" aspectratio="t"/>
       </v:shapetype><v:shape id="Picture_x0020_2" o:spid="_x0000_i1026" type="#_x0000_t75"
        style='width:159.75pt;height:37.5pt;visibility:visible;mso-wrap-style:square'>
        <v:imagedata src="file:///C:/Users/JISHNU~1/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
         o:title=""/>
       </v:shape><![endif]--><!-- [if !vml]--><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><img src="blob:https://app.v2.sama.live/00191c65-69f3-4f1c-9824-df92d2ecb42f" width="213" height="68"><!--[endif]--></span></span></strong></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 1.0pt 93.0pt 0cm 93.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong>An Online Dispute Resolution Institution</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 2.0pt 93.0pt 0cm 93.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;"><span style="mso-bookmark: _Hlk63180060;">Recognized by Ministry of Law &amp; Justice, Government of India</span><a style="color: #e03e2d;" href="https://www.sama.live/"><span style="mso-bookmark: _Hlk63180060;">&nbsp;</span></a></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;"> </span></p>
       <p style="text-align: center; margin: 2.0pt 93.0pt 0cm 93.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;"><a style="color: #e03e2d;" href="https://www.sama.live/"><span style="mso-bookmark: _Hlk63180060;">https://www.sama.live/</span></a><span style="mso-bookmark: _Hlk63180060;"> </span><span style="mso-bookmark: _Hlk63180060;">| </span><span style="mso-bookmark: _Hlk63180060;">help@odrways.com<u>&nbsp;| +91-9855755798</u></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 24.0pt 6.0pt 6.0pt 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong>Date</strong></span><span style="mso-bookmark: _Hlk63180060;">:#Notice_Sent_Date#&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;</span></span></p>
       <p style="margin: 24pt 6pt 6pt 0cm; text-align: right;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong>REF NO.</strong><strong>#complainId#</strong><strong>/2022</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 12.0pt 0cm 12.0pt 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong>&nbsp;</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 3.0pt 0cm 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><br></span><span style="mso-bookmark: _Hlk63180060;">To</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 7.0pt 0cm 12.0pt 0cm;"><span style="font-size: 12pt; font-family: 'times new roman', times, serif; color: #000000;">#respondantName#</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 7.0pt 0cm 12.0pt 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;">Dear Customer,</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 24.0pt 93.0pt 0cm 93.0pt;" align="center"><span style="text-decoration: underline;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000; text-decoration: underline;"><span style="mso-bookmark: _Hlk63180060;"><strong>SUBJECT- NOTICE TO RESOLVE PAYMENT DISPUTE WITH&nbsp;</strong></span><strong>#complainantName#</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 24.0pt 93.0pt 0cm 93.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>(In accordance with Section 21 of Arbitration and Conciliation Act, 1996)</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 4.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 4.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">Dear Customer,</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 4.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpFirst" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify; text-indent: -18.0pt; mso-list: l1 level1 lfo2;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">1.<span style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-family: Times New Roman, serif;">That you had approached the #complainantName#&nbsp;and applied for credit card by submitting application online through digital platform/ or to Branch of plaintiff Bank by complying the necessary formalities and upon submission of application followed by due authentication and acceptance of the applicable charges/interest and &ldquo;Terms &amp; Conditions&rdquo; governing the credit card facility,&nbsp;</span><span style="font-family: Times New Roman, serif;">#complainantName#&nbsp;issued a credit card bearing&nbsp;</span><span style="font-family: Times New Roman, serif;">#lan#&nbsp;to you. That you on its usage became bound by the terms and condition governing credit card facilities as applicable to the Credit Card holders upon accepting, retaining and utilising the said credit card.</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify; text-indent: -18.0pt; mso-list: l1 level1 lfo2;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">2.<span style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-family: Times New Roman, serif;">You started defaulting in making monthly/periodical payment of the utilized amount alongwith interest in favour of the claimant. Upon repeated reminders and follow-ups, you had failed and neglected to regularize the said Credit card dues and thus committed material breach of the terms and conditions of the said facility. You are now required to repay according to the terms and conditions of Credit Card Agreement </span><em>(hereinafter mentioned as Facility). </em><span style="font-family: Times New Roman, serif;">That as of&nbsp;</span><span style="font-family: Times New Roman, serif;">#duedate#, your total outstanding amount stands at&nbsp;</span><span style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"><span style="font-family: Times New Roman, serif;">#claimamount#/-</span><strong>&nbsp;</strong></span><span style="font-family: Times New Roman, serif;">under the said credit card facility, together with interest and other charges.</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify; text-indent: -18.0pt; line-height: normal; mso-list: l1 level1 lfo2;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">3.<span style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]-->According to the arbitration clause agreed by you as per which any dispute arising out of or in connection with the said facility shall be settled by conciliation/arbitration in accordance with Arbitration and Conciliation Act, 1996 read with Sama rules. The terms and conditions of the Credit Card Agreement are available here- </span><span style="color: #236fa1;"><a style="color: #236fa1;" href="https://www.icicibank.com/sitemap.html?aspxerrorpath=/managed-assets/docs/personal/cards/credit-cards/tnc_english.pdf." target="_blank" rel="noopener"><span style="mso-bookmark: _Hlk63180060;">https://www.icicibank.com/managed-assets/docs/personal/cards/credit-cards/tnc_english.pdf</span><span style="mso-bookmark: _Hlk63180060;">.</span></a></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify; text-indent: -18.0pt; line-height: normal; mso-list: l1 level1 lfo2;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">4.<span style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]--><span style="font-family: Times New Roman, serif;">That #complainantName# has now approached Sama for resolution of dispute and invoked the said clause 30.3 (XXX.3) of the Terms &amp; Conditions governing the Credit Card facility as agreed by you. That according to Clause 30.3 of the Credit Card Facility agreed by you, if the mediation or conciliation process does not resolve the Grievance or the Claim within the period stipulated in Sama rules or within a period of 21 days (whichever is earlier), then the Grievance or the Claim shall be taken forward for resolution by means of arbitration in terms of the applicable rules of Sama, and in accordance with the Arbitration and Conciliation Act, 1996. Such arbitration shall be conducted (including for recording of evidence or tendering of documents), concluded and administered online by Sama through its website/platform www.sama.live or mobile application.</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpMiddle" style="margin-left: 41.0pt; mso-add-space: auto; text-align: justify; text-indent: -18.0pt; line-height: normal; mso-list: l1 level1 lfo2;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><!-- [if !supportLists]--><span style="mso-list: Ignore;">5.<span style="font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; line-height: normal;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><!--[endif]-->The arbitral tribunal shall consist of an independent sole arbitrator appointed in accordance with the applicable arbitration rules of Sama. The seat of arbitration proceedings shall be Mumbai. The procedural law of arbitration shall be rules of Sama, which are available here- </span><span style="color: #236fa1;"><a style="color: #236fa1;" href="https://www.sama.live/rules_and_procedures-2021.php" target="_blank" rel="noopener"><span style="mso-bookmark: _Hlk63180060;">https://www.sama.live/rules_and_procedures-2021.php</span></a></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoListParagraphCxSpLast"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="line-height: 107%;">&nbsp;</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 4.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>What is Sama?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 4.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #236fa1;"><a style="color: #236fa1;" href="https://www.youtube.com/watch?v=kcjfttLq_1c" target="_blank" rel="noopener"><span style="mso-bookmark: _Hlk63180060;"><strong><em>[Watch this 90 second video to know Sama]</em></strong></span></a></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;">Sama&nbsp;is a neutral and independent Online Dispute Resolution (ODR) Institution, recognized by <em>the Ministry of Law and Justice, Government of India</em>, that specializes in helping people resolve disputes without the hassles of going to court. We believe in giving parties a chance to be heard and to create a space for amicable settlement of disputes. To know more about Sama, click </span><a style="color: #000000;" href="https://www.sama.live/"><span style="mso-bookmark: _Hlk63180060;">here</span></a><span style="mso-bookmark: _Hlk63180060;"><span class="MsoHyperlink">- </span></span><span style="text-decoration: underline;"><span style="color: #236fa1; text-decoration: underline;"><span style="mso-bookmark: _Hlk63180060;">www.sama.live</span><span style="mso-bookmark: _Hlk63180060;"> </span><span style="mso-bookmark: _Hlk63180060;">.</span></span></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>What is Conciliation?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">Conciliation is a way of settling disputes in a cost-effective, speedy and amicable manner with the assistance of a neutral expert who is called a &ldquo;Conciliator&rdquo;. The parties to a dispute get together to amicably discuss and settle the dispute in the presence of a conciliator in a fair and transparent manner. If the parties settle in the conciliation, they will be provided with a conciliation award by the Conciliator, which is fully legal and enforceable like a court decree according to Section 74 of Arbitration and Conciliation, 1996.</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>Who is a Conciliator?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">A conciliator is an independent and impartial trained dispute resolution expert and his/her role is to be<strong><em> absolutely neutral </em></strong>and help parties come up with solutions to solve the dispute instead of moving court. Our conciliator would even suggest creative solutions likely to result into a settlement agreement based on how disputes like yours have been resolved for other people.</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>Who will be the Conciliator?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">Sama will appoint a professional conciliator from a pool of conciliators available <span style="color: #236fa1;"><a style="color: #236fa1;" href="https://www.sama.live/neutrals.php" target="_blank" rel="noopener">here</a></span>. All Sama Conciliators are trained with years of legal experience and relevant subject matter expertise. They are not representatives of any party, and their primary role will be to understand your side of the story and help you in reaching the most suitable settlement. </span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>What if you don&rsquo;t like your Conciliator?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;">During the conciliation process, if you are unhappy with the Conciliator, you will be provided with an opportunity to raise the issue with the Sama Dispute Resolution Professional (DRP) Review Committee, which is specifically responsible to overlook the conciliation process and performance of the Conciliators, and will fully ensure that all your grievances are effectively addressed. <span style="mso-spacerun: yes;">&nbsp;</span>Basis your request, Sama has the right to reappoint a new conciliator for you. They will be reachable at help@odrways.com.</span><span style="mso-bookmark: _Hlk63180060;"> </span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong><em>Not sure whether to consent and settle the dispute via conciliation-arbitration? Do you have any queries?</em></strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;">Reach out to the Sama Support Team via call or whatsapp at </span><span style="mso-bookmark: _Hlk63180060;"><span style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">+91-98557-55798 or email at </span></span><span style="color: #236fa1;"><a style="color: #236fa1;" href="mailto:help@odrways.com"><span style="mso-bookmark: _Hlk63180060;"><span style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">help@odrways.com</span></span></a></span><span style="mso-bookmark: _Hlk63180060;"><span style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;"> </span></span><span style="mso-bookmark: _Hlk63180060;">to clarify any queries related to the process and figure out the most suitable path forward for you. </span></span><span style="font-family: 'times new roman', times, serif; font-size: 12pt;">Going to courts for such disputes can be extremely time consuming, expensive and mentally harrowing. Issues like these can be easily resolved without having to move court.&nbsp; &nbsp;</span><span style="font-family: 'times new roman', times, serif; font-size: 12pt;">Make use of this unique opportunity to settle your matter fully online and in an amicable manner! Click on the &ldquo;</span><strong style="font-family: 'times new roman', times, serif; font-size: 12pt;">CONSENT</strong><span style="font-family: 'times new roman', times, serif; font-size: 12pt;">&rdquo; button provided below, within 7 days of receiving the notice.</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em><span style="mso-spacerun: yes;">&nbsp; </span>Are you interested to participate?</em></strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 10.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;">In order to start the process and explore your settlement options, please choose one of the following options and click on the &ldquo;<strong>CONSENT</strong>&rdquo; button provided below:</span></span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 10.0pt;">&nbsp;</p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 12pt 0cm 0cm; text-align: center;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">#consentOptions#</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span><br style="mso-ignore: vglayout;" clear="ALL"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">After you have clicked on the &ldquo;<strong>Consent</strong>&rdquo; button, your conciliator will reach out to you to discuss possible solutions. If you do not provide consent within 21 days of receiving this notice, the case will be marked as a &ldquo;non-starter&rdquo; in conciliation and #complainantName# will have the right to take it forward to arbitration. </span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: justify; margin: 8.0pt 6.0pt 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <div style="mso-element: para-border-div; border: solid windowtext 1.0pt; mso-border-alt: solid windowtext .5pt; padding: 1.0pt 4.0pt 1.0pt 4.0pt; margin-left: 0cm; margin-right: 6.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span>
       <p style="text-align: justify; border: none; mso-border-alt: solid windowtext .5pt; padding: 0cm; mso-padding-alt: 1.0pt 4.0pt 1.0pt 4.0pt; margin: 8.0pt 0cm 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong><em>What happens if I do not participate in the proceedings?</em></strong></span></p>
       <span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span>
       <p style="text-align: justify; border: none; mso-border-alt: solid windowtext .5pt; padding: 0cm; mso-padding-alt: 1.0pt 4.0pt 1.0pt 4.0pt; margin: 8.0pt 0cm 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><em><strong>If you do not participate in the proceedings, you will miss out the chance to resolve the dispute amicably over the platform and subsequently </strong><strong>#complainantName#</strong><strong>&nbsp;may initiate legal proceedings, both civil and criminal, against you before Court/Tribunals/Arbitration at your own cost and expenses.</strong></em></span></p>
       <span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></div>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 12.0pt 6.0pt 12.0pt 0cm;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong><span style="mso-spacerun: yes;">&nbsp;</span>Authorized by Sama</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 9.0pt 0cm 0cm 5.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><!-- [if gte vml 1]><v:shape id="Picture_x0020_4"
        o:spid="_x0000_i1025" type="#_x0000_t75" style='width:84.75pt;height:84pt;
        visibility:visible;mso-wrap-style:square'>
        <v:imagedata src="file:///C:/Users/JISHNU~1/AppData/Local/Temp/msohtmlclip1/01/clip_image004.jpg"
         o:title="" grayscale="t" bilevel="t"/>
       </v:shape><![endif]--><!-- [if !vml]--><img src="https://www.linkpicture.com/q/Sama-Seal_2.jpeg" width="264" height="148" border="0"><!--[endif]--></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 9.0pt 0cm 0cm 5.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="mso-bookmark: _Hlk63180060;"><strong>Recognized by Ministry of Law and Justice, Government of India</strong></span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 9.0pt 0cm 0cm 5.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>&nbsp;</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="text-align: justify; line-height: normal;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="font-family: Times New Roman, serif;">For any further queries regarding this, please call on #dsmDetails-phone#&nbsp;or email at&nbsp;</span><span style="font-family: Times New Roman, serif;">#dsmDetails-email#.</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="text-align: justify; line-height: normal;"><span style="font-size: 12pt; font-family: 'times new roman', times, serif; color: #000000;">&nbsp;</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="text-align: justify; line-height: normal;"><span style="font-size: 12pt; font-family: 'times new roman', times, serif; color: #000000;">Looking forward to hearing from you.</span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="text-align: justify; line-height: normal;"><span style="font-size: 12pt; font-family: 'times new roman', times, serif; color: #000000;">Yours faithfully, </span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="line-height: normal;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><span style="font-family: Times New Roman, serif;">#dsmDetails-name#</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="line-height: normal;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;">Authorized signatory of <span style="font-family: Times New Roman, serif;">#complainantName#</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 9.0pt 0cm 0cm 5.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>&nbsp;</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="text-align: center; margin: 9.0pt 0cm 0cm 5.0pt;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>&nbsp;</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoNormal" style="line-height: normal;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>Disclaimer</strong><span style="font-family: Times New Roman, serif;">- Sama is a neutral institution, and is not a representative of #complainantName#. It is only providing neutral and independent administrative assistance to facilitate the dispute resolution, in pursuance of your agreement with </span><span style="background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">#complainantName#</span><span style="font-family: Times New Roman, serif;">.</span></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 9.0pt 0cm 0cm 5.0pt;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>&nbsp;</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p style="margin: 9.0pt 0cm 0cm 0cm;"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"><strong>&nbsp;</strong></span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #000000;"> </span></p>
       <p class="MsoFooter" style="text-align: center;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;">Registered under Odrways Solutions Private Limited| W-901, Rohan Jharokha 2, Yemalur, Near HAL Airport<br>Bangalore, 560038, Karnataka India| CIN: U74999KA2019PTC125645| Telephone:&nbsp;<a style="color: #e03e2d;" href="tel:+919855755798">+91 98557 55798</a>| </span></p>
       <p><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;"> </span></p>
       <p class="MsoFooter" style="text-align: center;" align="center"><span style="font-family: 'times new roman', times, serif; font-size: 12pt; color: #e03e2d;"><a style="color: #e03e2d;" href="https://www.sama.live/privacy_policy.php">Privacy Policy</a> &amp; <a style="color: #e03e2d;" href="https://www.sama.live/terms_and_condition.php">Terms &amp; Conditions</a></span></p>`,
        `uploads/sample_${idx}.pdf`
      );
    });

    await Promise.all(temp);

    return NextResponse.json({ message: "OK" }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ message: "OK" }, { status: 500 });
  }
};
