import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [val, setVal] = useState("");
  const temp =async () => {
    let res = await axios.get("/api/hello");
    setVal(res.data.name);
  };

  useEffect(()=>{
    temp();
  },[])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{val}</h1>
    </div>
  );
}
